name: tests

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'test/**'
      - '.github/workflows/test.yml'
      - 'package.json'

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install Dependencies, Build & Test
        run: |
          npm ci
          npm test
