name: tests

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'test/**'
      - '.github/workflows/test.yml'
      - 'package.json'

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install Dependencies, Build & Test
        run: |
          npm ci
          npm test
