name: npmjs

on:
  release:
    types: [published]

env:
  TAG_VERSION: "$(echo $GITHUB_REF | cut -d / -f 3)"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Run Tests (${{ env.TAG_VERSION }})
        run: |
          npm ci
          npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upgrade to ${{ env.TAG_VERSION }}
        run: ./.github/scripts/incr-version.sh ${{ env.TAG_VERSION }}

      - name: Publishing to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upgrade to ${{ env.TAG_VERSION }}
        run: ./.github/scripts/incr-version.sh ${{ env.TAG_VERSION }}

      - name: Publishing to GPR
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

  vdeploy:
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-gpr]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Increment Version
        run: |
          echo "bodyText=$(./.github/scripts/incr-version.sh $TAG_VERSION)" >> $GITHUB_ENV

      - name: Version PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update to ${{ env.TAG_VERSION }}
          title: Update package.json (${{ env.TAG_VERSION }})
          body: ${{ env.bodyText }}
          branch: update-version
          base: master
