name: npmjs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Run Tests
        run: |
          npm ci
          npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Increment Version
        run: ./.github/scripts/incr-version.sh ${{ github.ref_name }}
      - name: Publishing to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Increment Version
        run: ./.github/scripts/incr-version.sh ${{ github.ref_name }}
      - name: Publishing to GPR
        uses: JS-DevTools/npm-publish@v3
        with:
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: false

  vdeploy:
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-gpr]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Increment Version
        run: echo "bodyText=$(./.github/scripts/incr-version.sh ${{ github.ref_name }})" \
             >> $GITHUB_ENV

      - name: Version PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update to ${{ github.ref_name }}
          title: Update package.json (${{ github.ref_name }})
          body: ${{ env.bodyText }}
          branch: update-version
          base: master
