name: npmjs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: |
          npm ci
          npm test
          ./.github/scripts/incr-version.sh "$(echo $GITHUB_REF | cut -d / -f 3)"

      - name: Cacing Results
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifacts@v3

      - name: Publising to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://registry.npmjs.org/
          token: ${{secrets.NPM_TOKEN}}
          dry-run: true

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifacts@v3

      - name: Publishing to GPR
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://registry.npmjs.org/
          token: ${{secrets.GITHUB_TOKEN}}
          dry-run: true

  vdeploy:
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-gpr]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Tag Version
        id: new_version
        run: echo "VER=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

      - name: Update Version
        id: old_version
        run: echo "VER=$(./.github/scripts/incr-version.sh ${{ steps.new_version.outputs.VER }})" \
             >> $GITHUB_OUTPUT

      - name: Version PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update to ${{ steps.new_version.outputs.VER }}
          title: Update package.json (${{ steps.new_version.outputs.VER }})
          body: ${{ steps.old_version.outputs.VER }}
          branch: update-version
          base: master
